### ISSUE TITLE
Crackly audio on OSX

### ISSUE THREAD

**Issue by Xaeroxe** [RustAudio/rodio#225]
The Amethyst game engine has been receiving reports of crackly distorted audio on OSX. Has this been extensively tested on OSX? One contributor believed this may be due to Mutex use in rodio and cpal, possibly blocking the threads used to send samples through.

**Comment by mitchmindtree** [comment]
On macOS/iOS, the chain of dependencies are:

rodio <- cpal <- coreaudio-rs <- coreaudio-sys

I would start with the coreaudio-rs example and work my way up the stack until the crackling occurs to hone in on the exact crate where this is occurring. Another thing to keep in mind is that, due to the low latency required, I find I almost always have to compile rust in release for projects involving real-time audio streams or it will almost certainly crackle.

FWIW, we used CPAL (via nannou, not rodio) in a 100+ channel, real-time [spatial audio server](https://github.com/museumsvictoria/spatial_audio_server) for an exhibition about a year ago on an old Mac Mini and it ran fine. The museum has continued to use it for multiple exhibitions since and seemingly haven't had any issues, so I would be surprised if it was a performance problem in CPAL or coreaudio-rs.

Anyway, hope this helps!

**Comment by incon** [comment]
On macOS, I only get crackly from the `music_flac` example all other examples are working fine.

**Comment by yerke** [comment]
I can confirm that in debug mode only `music_flac` is crackly, but in release mode it sounds fine.

**Comment by paulirotta** [comment]
This and #266 on Linux make me think there is a need for buffering the output of Sinks. This of course should be tunable for delay-sensitive use cases.

**Comment by paulirotta** [comment]
Does the crackly go away when you add `.delay(Duration::new(0, 5000)` to the last `Source` before your `Sink`?

**Comment by yerke** [comment]
@paulirotta When I modified to `sink.append(rodio::Decoder::new(BufReader::new(file)).unwrap().delay(Duration::new(0, 5000)));` in `examples/music_flac.rs`, the crackly sound was still there in debug mode, but not in release mode. So the same as before.

**Comment by paulirotta** [comment]
Ok. Pity.

Have you tried https://crates.io/crates/thread-priority to max?

**Comment by Akirami** [comment]
Same issu here, not with a Sink but with DynamicMixer::mixer. 

The weird thing is the sound crakle only the first time i play it in a loop, the second time and all others loop are fine.

Same thing, no crackly sound once released.

@paulirotta This crate is not for MacOS.

**Comment by paulirotta** [comment]
Audio is crackly on all platforms with debug builds. audio_thread_priority looks like a good find (the other library author has not had time to add macOS support). Please let us know if that works and perhaps it would be a good addition to rodio
