### ISSUE TITLE
aac file doesn't play in rodio with error «invalid data»

### ISSUE THREAD

**Issue by Rrogntudju** [RustAudio/rodio#401]
I first opened an issue in symphonia: https://github.com/pdeljanov/Symphonia/issues/67

Please take a look at the symphonia maintainer answer.

**Comment by est31** [comment]
Interesting. I guess decode errors need to be ignored. PRs welcome!

**Comment by pdeljanov** [comment]
Just wanted to clarify something since my answer to the linked issue was a bit simplistic.

A decode error produced by `Decoder::decode` is not considered fatal. This is because if there is an error (corruption, invalid data, etc.), it's usually limited to that individual packet. The correct action is to just get a new packet and try again. However, a decode error anywhere else is fatal.

I plan to make fatal errors a distinct error kind in the future, but I haven't gotten to it yet unfortunately.

**Comment by est31** [comment]
Fixed by #403
