### ISSUE TITLE
Audio channels are sometimes reversed depending on debug and release builds

### ISSUE THREAD

**Issue by harudagondi** [RustAudio/rodio#444]
To reproduce:

Run `cargo run --example spatial`. Notice the sound starting from the right.

Run `cargo run --example spatial --release`. Notice the sound starting from the left.

Related to this comment:
- https://github.com/bevyengine/bevy/pull/6028#issuecomment-1253328622

**Comment by rparrett** [comment]
I can reproduce this.

macOS 12.6
MacBook Pro (M1 Max)

Although it seems unlikely that this is related to spatial audio specifically, and I'd imagine the issue is upstream in CPAL and only coincidentally related to the release/debug setting.

Here's a test wav that should play tones in the right and then left channels.

[RL.zip](https://github.com/RustAudio/rodio/files/9668031/RL.zip)

When I play this with the `music_wav` example, I always hear a tone on the left first, no matter the debug/release setting.

**Comment by harudagondi** [comment]
Using @rparrett's audio file, I tested it with kira and oddio (both using cpal) and can confirm that this is an issue on rodio's end, not on cpal. Both kira and oddio produce the correct output.

**Comment by harudagondi** [comment]
It seems that this plays differently for other people. bevyengine/bevy#6122 and [this comment](https://github.com/bevyengine/bevy/pull/6028#discussion_r982925270) have it reversed (correct in debug, wrong in release).
