### ISSUE TITLE
Include `libsdl2-dev` as default dependency for Linux systems

### ISSUE THREAD

**Issue by GyulyVGC** [RustAudio/rodio#466]
On Linux, `rodio` doesn't compile, as already described in #200, until  a missing dependency is installed.

Personally, I solved with: `sudo apt install libsdl2-dev`.

However, I'm developing an application that depends on `rodio` and it'd be cool for my Linux users to not have to worry about installing any additional dependency.

Is there a way to achieve that?

**Comment by est31** [comment]
Unfortunately you have to ask your users to install the apt packages beforehand (or other linux packages), as cargo does not deal with them. Regarding sdl, actually we need alsa bindings only. sdl is not used by rodio (or cpal, which handles the cross platform part). See the packages listed in the issue you linked.

On userland, Linux has no clear separation between OS API and "libraries", so applications targetting linux instead have to link to specific libraries, like Alsa for example. So instead of being able to install one OS "SDK", there are a bunch of smaller libraries instead.
