### ISSUE TITLE
Idea of implementing AGC (Automatic Gain Control)

### ISSUE THREAD

**Issue by UnknownSuperficialNight** [RustAudio/rodio#620]
I was thinking for the sink: would you be okay with me looking into making a pull request for implementing AGC for the sink? This would allow it to dynamically adjust the audio volume by increasing the gain if the audio level is too low or decreasing it if the level is too high. 

Apologies if this is already implemented somewhere; I checked the documentation but could not find a mention of it.

**Comment by dvdsk** [comment]
Thats a pretty cool idea :+1: , I would love to have it!

I suggest making a `Source` instead of modifying the Sink. A source is easier to test and would allow users to use automatic gain control even if they do not use the `Sink`. 

Take a look at the `Source` trait [docs](https://docs.rs/rodio/latest/rodio/source/trait.Source.html) . A good example `Source` too look at would be the amplify `Source`.

Feel free to make a PR, it does not need to be done if you open it as draft I'll take a look every once in a while and see if I can drop some feedback/help out.
